### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by Abro61209** [poobarfoob/l2tunnel-kai-guide#1]
I ran the setup.bat, picked my ethernet controller, and input the MAC address from my dashboard into the setup.bat and it says tunnel.bat was created and all I have to do is launch and I'm good to go. I launch it and the command prompt window shows up for a split second and closes immediately. Doesn't stay open long enough to show an error or text or anything.

**Comment by poobarfoob** [comment]
Hm, can you try launching it through command prompt and seeing what it spits out?

**Comment by Abro61209** [comment]
I figured it out. You must input the MAC address like this: XX:XX:XX:XX:XX:XX

Dashes instead of colons didn't work for me, neither did no dashes and no colons.

**Comment by poobarfoob** [comment]
Ok, im going to close this issue then. 👍
